version: "3.9"
services:
  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - HOST=db
      - PORT=5432
      - USER=user
      - PASSWORD=password
      - SSLMODE=disable
      - DATABASE=backend
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB=backend
      POSTGRES_USER=user
      POSTGRES_PASSWORD=password
      PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  