version: "3.9"
services:
  bot:
    build: .
    restart: always
    depends_on:
      - dbr
      - dbw
    environment:
      - HOST_READ=dbr
      - HOST_WRITE=dbw
  dbr:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB=backend
      POSTGRES_USER=user
      POSTGRES_PASSWORD=password
      PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_read/data:/var/lib/postgresql/data
  dbw:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB=backend
      POSTGRES_USER=user
      POSTGRES_PASSWORD=password
      PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_write/data:/var/lib/postgresql/data
  