POST https://mail.leaguemail.ru/contacts HTTP/1.0

# Host: mail.leaguemail.ru
# Connection: close
# Content-Length: 247
# Content-Type: application/xml;charset=UTF-8

<XIMSS>
    <listDirectory limit="4" filter="filter" id="1">
        <field>example</field>
    </listDirectory>
</XIMSS>