POST https://mail.leaguemail.ru/contacts HTTP/1.1

# Host: mail.leaguemail.ru
# Connection: close
# Content-Length: 247
# Content-Type: text/xml;charset=UTF-8

<XIMSS>
    <listDirectory limit="4" filter="(|(mail=21*))" id="66">
        <field>cn</field>
        <field>mail</field>
        <field>o</field>
        <field>ou</field>
        <field>telephoneNumber</field>
        <field>mobile</field>
        <field>userCertificate</field>
    </listDirectory>
</XIMSS>